logLevel = "info"
kafkaBrokers = ["kafka:9093"]
kafkaTopic = "feed-fusion-logs"
kafkaGroupID = "logkeeper-group"

ElasticSearchNodes = ["http://elasticsearch:9200"]
elasticSearchIndex = "feed-fusion-logs"

numWorkers = 4
