serviceName = "APIGateway"
httpAddr = ":8088"
logLevel = "info"
kafkaAddr = "kafka:9093"
kafkaTopic = "feed-fusion-logs"
kafkaBatch = 0

[subServices.Aggregator]
url = "http://aggregator:8066"
name = "Aggregator"

[subServices.Comments]
url = "http://comments:8077"
name = "Comments"

[subServices.Censor]
url = "http://censor:8055"
name = "Censor"
